-- Spanish problem taxonomy: translate topics and classifications, merge duplicates.
-- Reuses ids, so problems keep their classifications; merged ones move to the kept id.
USE jol;

START TRANSACTION;

UPDATE topic SET name = 'Estructuras de datos' WHERE topic_id = 1;
UPDATE topic SET name = 'Estructuras de datos avanzadas' WHERE topic_id = 17;
UPDATE topic SET name = 'Búsqueda y ordenamiento' WHERE topic_id = 2;
UPDATE topic SET name = 'Técnicas algorítmicas' WHERE topic_id = 7;
UPDATE topic SET name = 'Programación dinámica' WHERE topic_id = 3;
UPDATE topic SET name = 'Matemáticas y teoría de números' WHERE topic_id = 4;
UPDATE topic SET name = 'Combinatoria y probabilidad' WHERE topic_id = 14;
UPDATE topic SET name = 'Teoría de juegos' WHERE topic_id = 19;
UPDATE topic SET name = 'Grafos' WHERE topic_id = 15;
UPDATE topic SET name = 'Cadenas' WHERE topic_id = 13;
UPDATE topic SET name = 'Geometría' WHERE topic_id = 5;
UPDATE topic SET name = 'Ad hoc e implementación' WHERE topic_id = 8;

UPDATE classification SET topic_id = 1, name = 'Pilas' WHERE classification_id = 1;
UPDATE classification SET topic_id = 1, name = 'Colas' WHERE classification_id = 2;
UPDATE classification SET topic_id = 1, name = 'Colas dobles (deque)' WHERE classification_id = 3;
UPDATE classification SET topic_id = 1, name = 'Arreglos' WHERE classification_id = 4;
UPDATE classification SET topic_id = 1, name = 'Arreglos bidimensionales' WHERE classification_id = 5;
UPDATE classification SET topic_id = 1, name = 'Conjuntos disjuntos (DSU)' WHERE classification_id = 6;
UPDATE classification SET topic_id = 1, name = 'Colas de prioridad' WHERE classification_id = 8;
UPDATE classification SET topic_id = 1, name = 'Matrices' WHERE classification_id = 11;
UPDATE classification SET topic_id = 4, name = 'Exponenciación de matrices' WHERE classification_id = 12;
UPDATE classification SET topic_id = 2, name = 'Búsqueda binaria' WHERE classification_id = 13;
UPDATE classification SET topic_id = 15, name = 'DFS (búsqueda en profundidad)' WHERE classification_id = 14;
UPDATE classification SET topic_id = 15, name = 'BFS (búsqueda en anchura)' WHERE classification_id = 15;
UPDATE classification SET topic_id = 15, name = 'Dijkstra' WHERE classification_id = 16;
UPDATE classification SET topic_id = 7, name = 'Backtracking' WHERE classification_id = 17;
UPDATE classification SET topic_id = 4, name = 'Operaciones con bits' WHERE classification_id = 18;
UPDATE classification SET topic_id = 7, name = 'Fuerza bruta' WHERE classification_id = 19;
UPDATE classification SET topic_id = 7, name = 'Divide y vencerás' WHERE classification_id = 20;
UPDATE classification SET topic_id = 7, name = 'Algoritmos voraces (greedy)' WHERE classification_id = 21;
UPDATE classification SET topic_id = 2, name = 'Ordenamiento' WHERE classification_id = 22;
UPDATE classification SET topic_id = 2, name = 'Búsqueda ternaria' WHERE classification_id = 23;
UPDATE classification SET topic_id = 2, name = 'Dos punteros' WHERE classification_id = 24;
UPDATE classification SET topic_id = 3, name = 'Programación dinámica' WHERE classification_id = 25;
UPDATE classification SET topic_id = 3, name = 'DP con máscaras de bits' WHERE classification_id = 26;
UPDATE classification SET topic_id = 3, name = 'Optimización de DP' WHERE classification_id = 27;
UPDATE classification SET topic_id = 3, name = 'Mochila (knapsack)' WHERE classification_id = 28;
UPDATE classification SET topic_id = 7, name = 'Meet in the middle' WHERE classification_id = 29;
UPDATE classification SET topic_id = 14, name = 'Combinatoria' WHERE classification_id = 30;
UPDATE classification SET topic_id = 19, name = 'Teoría de juegos' WHERE classification_id = 31;
UPDATE classification SET topic_id = 5, name = 'Geometría' WHERE classification_id = 32;
UPDATE classification SET topic_id = 4, name = 'Matemáticas' WHERE classification_id = 33;
UPDATE classification SET topic_id = 4, name = 'Teoría de números' WHERE classification_id = 34;
UPDATE classification SET topic_id = 4, name = 'Criba de Eratóstenes' WHERE classification_id = 36;
UPDATE classification SET topic_id = 4, name = 'Teorema chino del resto' WHERE classification_id = 37;
UPDATE classification SET topic_id = 4, name = 'Factorización' WHERE classification_id = 38;
UPDATE classification SET topic_id = 15, name = 'Grafos (general)' WHERE classification_id = 39;
UPDATE classification SET topic_id = 5, name = 'Envolvente convexa' WHERE classification_id = 40;
UPDATE classification SET topic_id = 15, name = 'Caminos más cortos' WHERE classification_id = 43;
UPDATE classification SET topic_id = 15, name = 'Componentes fuertemente conexas (Tarjan)' WHERE classification_id = 44;
UPDATE classification SET topic_id = 15, name = 'Árboles' WHERE classification_id = 45;
UPDATE classification SET topic_id = 4, name = 'Transformada rápida de Fourier (FFT)' WHERE classification_id = 47;
UPDATE classification SET topic_id = 1, name = 'Hashing' WHERE classification_id = 48;
UPDATE classification SET topic_id = 7, name = 'Recursión' WHERE classification_id = 49;
UPDATE classification SET topic_id = 7, name = 'Línea de barrido' WHERE classification_id = 52;
UPDATE classification SET topic_id = 15, name = '2-SAT' WHERE classification_id = 54;
UPDATE classification SET topic_id = 8, name = 'Ad hoc' WHERE classification_id = 55;
UPDATE classification SET topic_id = 7, name = 'Algoritmos constructivos' WHERE classification_id = 56;
UPDATE classification SET topic_id = 13, name = 'Análisis de expresiones' WHERE classification_id = 57;
UPDATE classification SET topic_id = 14, name = 'Probabilidad' WHERE classification_id = 58;
UPDATE classification SET topic_id = 7, name = 'Consultas (queries)' WHERE classification_id = 59;
UPDATE classification SET topic_id = 7, name = 'Algoritmos aleatorizados' WHERE classification_id = 60;
UPDATE classification SET topic_id = 7, name = 'Planificación (scheduling)' WHERE classification_id = 61;
UPDATE classification SET topic_id = 17, name = 'Descomposición en raíz cuadrada' WHERE classification_id = 63;
UPDATE classification SET topic_id = 8, name = 'Principiante' WHERE classification_id = 64;
UPDATE classification SET topic_id = 4, name = 'Aritmética básica' WHERE classification_id = 65;
UPDATE classification SET topic_id = 8, name = 'Muy fácil' WHERE classification_id = 66;
UPDATE classification SET topic_id = 8, name = 'Trivial' WHERE classification_id = 67;
UPDATE classification SET topic_id = 13, name = 'Secuencias de paréntesis' WHERE classification_id = 69;
UPDATE classification SET topic_id = 8, name = 'Imprimir' WHERE classification_id = 71;
UPDATE classification SET topic_id = 8, name = 'Suma' WHERE classification_id = 72;
UPDATE classification SET topic_id = 8, name = 'Implementación' WHERE classification_id = 73;
UPDATE classification SET topic_id = 14, name = 'Permutaciones' WHERE classification_id = 76;
UPDATE classification SET topic_id = 14, name = 'Combinaciones' WHERE classification_id = 77;
UPDATE classification SET topic_id = 14, name = 'Coeficientes binomiales' WHERE classification_id = 78;
UPDATE classification SET topic_id = 14, name = 'Principio del palomar' WHERE classification_id = 79;
UPDATE classification SET topic_id = 14, name = 'Inclusión-exclusión' WHERE classification_id = 80;
UPDATE classification SET topic_id = 14, name = 'Problemas de conteo' WHERE classification_id = 81;
UPDATE classification SET topic_id = 15, name = 'Árbol de expansión mínima' WHERE classification_id = 84;
UPDATE classification SET topic_id = 15, name = 'Flujo en redes' WHERE classification_id = 85;
UPDATE classification SET topic_id = 15, name = 'Emparejamiento (matching)' WHERE classification_id = 86;
UPDATE classification SET topic_id = 15, name = 'Coloreo de grafos' WHERE classification_id = 87;
UPDATE classification SET topic_id = 15, name = 'Grafos planares' WHERE classification_id = 88;
UPDATE classification SET topic_id = 13, name = 'Búsqueda de patrones' WHERE classification_id = 89;
UPDATE classification SET topic_id = 13, name = 'Estructuras de sufijos' WHERE classification_id = 90;
UPDATE classification SET topic_id = 13, name = 'Trie' WHERE classification_id = 91;
UPDATE classification SET topic_id = 13, name = 'Algoritmo Z' WHERE classification_id = 92;
UPDATE classification SET topic_id = 13, name = 'Rabin-Karp' WHERE classification_id = 95;
UPDATE classification SET topic_id = 17, name = 'Árbol de segmentos' WHERE classification_id = 96;
UPDATE classification SET topic_id = 17, name = 'Árbol de Fenwick (BIT)' WHERE classification_id = 97;
UPDATE classification SET topic_id = 17, name = 'Árbol splay' WHERE classification_id = 98;
UPDATE classification SET topic_id = 17, name = 'Árbol AVL' WHERE classification_id = 99;
UPDATE classification SET topic_id = 17, name = 'Treap' WHERE classification_id = 100;
UPDATE classification SET topic_id = 17, name = 'Descomposición heavy-light' WHERE classification_id = 101;
UPDATE classification SET topic_id = 17, name = 'Estructuras persistentes' WHERE classification_id = 102;
UPDATE classification SET topic_id = 4, name = 'Aritmética modular' WHERE classification_id = 104;
UPDATE classification SET topic_id = 4, name = 'Álgebra lineal' WHERE classification_id = 107;
UPDATE classification SET topic_id = 4, name = 'Multiplicación rápida de matrices' WHERE classification_id = 109;
UPDATE classification SET topic_id = 8, name = 'Simulación' WHERE classification_id = 110;
UPDATE classification SET topic_id = 19, name = 'Juegos de estrategia' WHERE classification_id = 112;
UPDATE classification SET topic_id = 13, name = 'KMP' WHERE classification_id = 115;
UPDATE classification SET topic_id = 2, name = 'Ordenamiento con criterio propio' WHERE classification_id = 116;
UPDATE classification SET topic_id = 13, name = 'Manipulación de cadenas' WHERE classification_id = 117;
UPDATE classification SET topic_id = 13, name = 'Boyer-Moore' WHERE classification_id = 118;
UPDATE classification SET topic_id = 13, name = 'Aho-Corasick' WHERE classification_id = 119;

INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 97 FROM problem_classification WHERE classification_id = 7;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 96 FROM problem_classification WHERE classification_id = 9;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 90 FROM problem_classification WHERE classification_id = 10;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 38 FROM problem_classification WHERE classification_id = 35;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 6 FROM problem_classification WHERE classification_id = 41;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 85 FROM problem_classification WHERE classification_id = 42;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 18 FROM problem_classification WHERE classification_id = 46;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 96 FROM problem_classification WHERE classification_id = 50;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 90 FROM problem_classification WHERE classification_id = 51;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 18 FROM problem_classification WHERE classification_id = 53;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 52 FROM problem_classification WHERE classification_id = 62;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 55 FROM problem_classification WHERE classification_id = 68;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 32 FROM problem_classification WHERE classification_id = 74;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 21 FROM problem_classification WHERE classification_id = 75;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 39 FROM problem_classification WHERE classification_id = 82;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 43 FROM problem_classification WHERE classification_id = 83;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 119 FROM problem_classification WHERE classification_id = 93;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 115 FROM problem_classification WHERE classification_id = 94;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 34 FROM problem_classification WHERE classification_id = 103;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 31 FROM problem_classification WHERE classification_id = 105;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 58 FROM problem_classification WHERE classification_id = 106;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 47 FROM problem_classification WHERE classification_id = 108;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 34 FROM problem_classification WHERE classification_id = 111;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 65 FROM problem_classification WHERE classification_id = 113;
INSERT IGNORE INTO problem_classification (problem_id, classification_id) SELECT problem_id, 22 FROM problem_classification WHERE classification_id = 114;
DELETE FROM problem_classification WHERE classification_id IN (7, 9, 10, 35, 41, 42, 46, 50, 51, 53, 62, 68, 74, 75, 82, 83, 93, 94, 103, 105, 106, 108, 111, 113, 114);
DELETE FROM classification WHERE classification_id IN (7, 9, 10, 35, 41, 42, 46, 50, 51, 53, 62, 68, 74, 75, 82, 83, 93, 94, 103, 105, 106, 108, 111, 113, 114);
DELETE FROM topic WHERE topic_id IN (6, 9, 16, 18);

COMMIT;
