<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.22" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../ExternalServices/ScheduleManager/src/Core/Application/Services/ScheduleManager.Core.Application.Services.csproj" />
    <ProjectReference Include="../../../../ExternalServices/ScheduleManager/src/Infrastructure/ScheduleManager.Infrastructure.Database/ScheduleManager.Infrastructure.Database.csproj" />
    <ProjectReference Include="..\..\Core\Domain\Models\OnlineJudgeAdmin.Core.Domain.Models.csproj" />
    <ProjectReference Include="..\..\Core\Application\Validators\OnlineJudgeAdmin.Core.Application.Validators.csproj" />
    <ProjectReference Include="..\..\Core\Domain\Abstractions\OnlineJudgeAdmin.Core.Domain.Abstractions.csproj" />
    <ProjectReference Include="..\..\Core\Application\Services\OnlineJudgeAdmin.Core.Application.Services.csproj" />
    <ProjectReference Include="..\..\Infrastructure\OnlineJudgeAdmin.Infrastructure.Database\OnlineJudgeAdmin.Infrastructure.Database.csproj" />
    <ProjectReference Include="..\..\Infrastructure\OnlineJudgeAdmin.Infrastructure.AwsS3\OnlineJudgeAdmin.Infrastructure.AwsS3.csproj" />
    <ProjectReference Include="..\..\Infrastructure\OnlineJudgeAdmin.Infrastructure.FileSystemLocalManager\OnlineJudgeAdmin.Infrastructure.FileSystemLocalManager.csproj" />
    <ProjectReference Include="..\..\Infrastructure\OnlineJudgeAdmin.Infrastructure.IdeIntegration\OnlineJudgeAdmin.Infrastructure.IdeIntegration.csproj" />

  </ItemGroup>
  

</Project>
